### ISSUE TITLE
cPRI as the Radio interface

### ISSUE THREAD

**Issue by VA7DBI** [M17-Project/rru-rf-hw#1]
is there any thought being given to using [cPRI](https://en.wikipedia.org/wiki/Common_Public_Radio_Interface) as the interface to the RRU?

**Comment by sp5wwp** [comment]
Interesting, but not yet. This is all in very early stage. I'll most likely start with Ethernet (over optical fiber).

**Comment by sp5wwp** [comment]
Closing as out of scope.
