### ISSUE TITLE
Hardware Choices

### ISSUE THREAD

**Issue by tomhajjar** [M17-Project/rru-rf-hw#6]
1. Is the unit Full or Half Duplex? If Half, why no T/R switch?

2. Why use a bi-directional coupler and log amps on TX output? APC only needs a resistive divider feeding a detector IC like LTC5505.

3. Why use an output isolator? The RA60H3847 can handle fairly high VSWR.

**Comment by sp5wwp** [comment]
1. Full duplex with 2 ports. No T/R switch needed.
2. Bi-directional coupler is used to measure SWR.
3. "Fairly high SWR" is not enough, we wanted the output to be bulletproof.
